### ISSUE TITLE
Disable ability to add users if the user doesn't have access to modify group

### ISSUE THREAD

**Issue by rnowosielski** [Cimpress/react-cimpress-users#3]
The component should check beforehand whether the user has access rights to list users and modify the permission group and grey out the options that are not feasible for the user.

Looking at the logs I see a lot of cases when users are trying to add a user to the group but they encounter error

- forbidden (on trying to fetch user suggestions)
- forbidden, user doesn't have rights to modify group when trying to add user

**Comment by istanishev** [comment]
#4 is addressing these to some extent. Unfortunately, it is not trivial to really answer in advance if a specific operation would succeed or not. The chanage in #4 will disable the 'add' button if searching for users returns 403. It would also amend the error message in case of 403 when a user is trying to grant a role that he/she doesnt have (eg. "reader" is trying to grant "editor" role)
